[package]
name = "lark"
version = "0.1.0"
authors = ["Tyler Saunders"]
edition = "2021"

[dependencies]
if_chain = "1.0.2"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_chacha = "0.3.1"
